[[installation-and-configuration]]
Installation and configuration
------------------------------

The platypus developer's kit all-in-one bundle contains Platypus.js IDE,
Platypus.js runtime and Apache Tomcat 8 software packages.

_____________________________________________________________________________________________
*Note*

Platypus.js runtime installation instructions are provided in the
Administration Guide.
_____________________________________________________________________________________________

[[system-requirements]]
System requirements
-------------------

System requirements for installing the developer's kit on a computer
includes:

* 32-bit (x86) or 64-bit (x64) CPU, 1 GHz or above
* 2 GB (for 32-bit system) or 3 GB (for 64-bit system) RAM
* 10 GB of free disk space
* Operating system with graphical user interface: Windows or Linux
* Oracle JDK 8.40+
* Internet access for updates downloading

[[installation-guide]]
Installation guide
------------------

To install the developer's kit, perform the following actions:

1.  Run the `platypusdesigner-windows.exe` file for Windows OS or
`platypusdesigner-linux.sh` for Linux. The Linux user must have access
rights to launch the installer.
2.  Click Next to proceed to the next installation step.
3.  Read licensing terms and conditions, check the I accept the terms of
the license agreement option to accept and click Next to proceed to the
next step.
4.  Select applications to be installed (Platypus application designer, Platypus.js runtime and Apache tomcat).
4.  Select the applications installation directories and options for
creating shortcuts on the desktop and in the installed programs menu and click Next to proceed to the next step.
5.  Click Install to start selected applications installation process.
6.  After the installation process is finished, click Finish.

__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

Specify the path to the JDK in the `jdkhome` parameter in the Platypus
Application Designer configuration file at
`platypusdesigner/etc/platypusdesigner.conf`, if the its installation
location is other than default. Incorrect value of the `jdkhome`
parameter can lead to errors which may occur when launching the
designer.
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

To remove Platypus.js runtime from you computer, perform the
following actions:

1.  Use the your OS standard mechanism of programs removal, as an
alternative, use the `uninstall.exe` program for Windows or
`uninstall.sh` for Linux from the installation directory.
2.  Confirm the components removal by clicking Finish button.

To remove Platypus Application Designer from you computer, perform the
following actions:

1.  Use the your OS standard mechanism of programs removal, as an
alternative, use the `uninstall.exe` program for Windows or
`uninstall.sh` for Linux from the installation directory.
2.  Confirm the components removal by clicking Finish button. If
necessary, select the option of removing configuration data from the
user's directory.

To remove Apache tomcat from you computer if it was installed using platypus developer's kit all-in-one installer, perform the
following actions:

1.  Use the your OS standard mechanism of programs removal, as an
alternative, use the `uninstall.exe` program for Windows or
`uninstall.sh` for Linux from the installation directory.
2.  Confirm the components removal by clicking Finish button.

[[configuration-tips]]
Configuration tips
------------------

Platypus Application Designer supports localization of menus, messages
texts, etc. Currently, the following languages are supported:

* English
* Russian

The localization language is selected automatically when you launch the
application designer according to the regional settings of the operating
system.

To force the change of the localization language:

* Edit the Platypus Application Designer configuration file — append the
`default_options` parameter with the `--locale ru:RU` or
`--locale en:US` option.
* Restart the application designer.

You can also change the application designer localization language by
adding the `--locale ru:RU` or `--locale en:US` option to the command
line for launching the Platypus Application Designer.

Platypus Application Designer supports connection of the various user
interface Look and Feel (L&F). There are L&Fs for specific operating
systems, universal styles (`Metal` and `Nimbus`), and LaFs which can be
supplied by third-party developers.

To change the Application Designer L&F:

* Edit the designer configuration file — append the `default_options`
parameter with the `--laf` option, where LaF corresponds to the name of
LaF or full name of the LaF class. If the third-party LaF is used, it is
also necessary to include the style library into the path which can be
accessed by the Application Designer classloader.
* Restart the application designer.

[[runtime-environment-setup]]
Runtime environment setup
-------------------------

The Platypus.js runtime is required to start, debug and deploy
it's applications. You must specify the path to the runtime directory
for the Platypus Application Designer to be able to run and debug your
applications.

Specify the location of the Platypus.js runtime directory in the computer's
file system:

* Select Tools Platypus Platform in the main menu of a the designer.
* In the selection dialog, specify path to the Platypus.js
directory.

Add the J2EE server instance which can be used to launch the Platypus
application:

* In the Services window of the Servers node context menu select the Add
server... item.
* In the J2EE server adding wizard, select the server type, server name,
and specify its preferences: path to the server directory,
administrator's login and password.

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*
If Platypus.js runtime and Platypus application designer were installed using
platypus developer's kit all-in-one installer, Platypus.js location will be specified already.
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
