[[развертывание-приложений-и-миграции-бд]]
Развертывание приложений и миграции БД
--------------------------------------

Развертывание — это процесс распространения готового приложения для
установки или обновления на рабочем сервере. На рабочем сервере
приложение Platypus целиком располагается в базе данных, либо в виде
каталога на жестком диске.

Механизм миграций обеспечивает сохранение и восстановление конфигурации
и начальных данных в базе данных.

Приложения Platypus поставляются в следующих вариантах:

* на компакт или DVD диске;
* через Интернет - в виде архивного файла в формате zip.

В случае поставки приложения Platypus в виде архивного файла распакуйте
его содержимое в удобное для вас место на жестком диске.

После распаковки, каталог будет иметь следующую структуру:

* `appDirectory/`
** `src/`
** `db/`
** `platypus.xml`

Каталог приложения Platypus соответствует проекту приложения готового
как для развертывания и исполнения, так и для модификации в Platypus
Application Designer.

Каталог приложения содежит конфигурационный файл `platypus.xml`, каталог
`src`, содержащий элементы приложения и каталог `db` в котором
содержатся миграции баз данных, а также включать файлы конфигруации
дизайнера `project.properties` и `private.properties`.

База данных в которую развертывается приложение включает в себя
системные таблицы и произвольное количество рабочих таблиц. При
развертывании системные таблицы создаются автоматически.

К системным таблицам относятся:

* `MTD_ENTITIES` — в данной таблице хранится исполняемое приложение в
виде древовидной структуры;
* `MTD_USERS` и `MTD_GROUPS` — таблицы пользователей и их групп при
работе со встроенным пространством пользователей, для информации смотри
раздел Безопасность.
* `MTD_VERSION` — в данной таблице хранится информация о текущей версии
хранилища данных приложения.

После развертывания в БД каждый элемент приложения представляет собой
одну запись в таблице `MTD_ENTITIES`.

Команда запуска утилиты развертывания и миграций БД имеет следующий вид:

-----------------------------
java -jar PlatypusDeploy.jar 
-----------------------------

где OPTIONS - команда развертывания или миграции и набор её параметров.

Описание команд относящиеся к операции развертывания импорта и миграций
смотрите в подразделах относящихся к развертыванию и миграциям БД.

.Параметры команд развертывания и миграций
[cols="<,<",]
|=======================================================================
|Параметр |Описание

|`-ap APP_PATH` |Путь к папке, содержащей готовое приложение Platypus.
Если этот параметр не задан, то будет использована текущая папка.

|`-dbuser DB_USER` |Имя пользователя для авторизации в БД.

|`-dbpassword DB_PASSWORD` |Пароль пользователя для авторизации в БД.

|`-dbschema DB_SCHEMA` |Схема БД.
|=======================================================================

______________________________________________________________________________________________________________________
*Note*

Действия по развертыванию и обновлению приложения также могут быть
выполнены при помощи Platypus Application Designer.
______________________________________________________________________________________________________________________

[[развертывание-и-импорт-приложения]]
Развертывание и импорт приложения
---------------------------------

_____________________________________________________________________________________
*Important*

Перед выполнением обновления приложения произведите резервное
копирование рабочей БД.
_____________________________________________________________________________________

Во время процесса разработки приложение находится в каталоге на диске,
при этом оно может запускаться для отладки и тестирования
непосредственно с диска. Для промышленной эксплуатации приложение
рекомендуется развертывать в базу данных.

.Команды развертывания и импорта приложения
[cols="<,<",]
|====================================================
|Параметр |Описание
|`-deploy` |Развертывает приложение с диска в БД.
|`-undeploy` |Удаляет приложение из БД.
|`-import` |Импортирует приложение из БД на диск.
|====================================================

В случае если параметры настройки соеденения с БД или имени пользвателя
и пароля Platypus не заданы в опциях, информация о соденении с БД будет
прочитана из файла настроек `platypus.xml` папки приложения.

Пример команды импорта приложения из БД:

--------------------------------------------------------------------------------------------------------------------------------------------------------
java -jar PlatypusDeploy.jar -import -ap ~/apps/testApp -url jdbc:oracle:thin:@serverHost:1521:adb -dbuser user1 -dbpassword secret -dbschema testschema
--------------------------------------------------------------------------------------------------------------------------------------------------------

Platypus Application Server и Platypus Client не требуют перезапуска
после обновления рабочего приложения.

[[миграции-бд]]
Миграции БД
-----------

Конфигурация базы данных приложения Platypus хранится в виде
последовательных миграций, которые применяются последовательно для
обеспечения корректной работы обновлений схемы и данных в БД. Каждое
изменение структуры или служебных данных представляет собой файл
миграции, название которого соответствует версии изменений, начиная с 1.
Для каждой новой миграции имя файла получается путем прибавления единицы
к максимальному номеру версии для данного приложения. Файлы миграций
могут быть двух типов:

* мгновенный снимок метаданных БД, с расширением `.xdm`;
* пакет SQL команд для добавления и/или изменения служебных данных, с
расширением `.batch`;

.Команды создания и применения миграций БД
[cols="<,<",]
|=======================================================================
|Параметр |Описание

|`-apply` |Применяет набор миграций к БД. Применяются те миграции, номер
которых больше текущей версии БД.

|`-undeploy` |Удаляет приложение из БД.

|`-snapshot` |Создает новую миграцию - снимок метаданных БД, при этом
версия БД устанавливается соответсвующей этой миграции.

|`-batch` |Создает новую пустую пакетную миграцию, при этом версия БД
устанавливается соответсвующей этой миграции.

|`-clean` |Производит очистку каталога миграций, удаляя те миграции,
которые не применяются.

|`-getver` |Возвращает текущую версию БД.

|`-setver` |устанавливает текущую версию БД в VERSION — целое,
неотрицательное число.
|=======================================================================

В случае если настройка соеденения с БД или имя пользвателя и пароля
Platypus не заданы в переметрах, информация о соеденении с БД будет
прочитана из файла настроек `platypus.xml` папки приложения.

При применении миграций к БД используется только последний моментальный
снимок структуры БД, а также все моментальные снимки которые идут
непосредственно перед пакетами SQL команд, остальные файлы миграций
игнорируются и могут быть удалены командой `-clean`.

Пример применения миграций к БД:

------------------------------------------------------
java -jar PlatypusDeploy.jar -apply -ap ~/apps/testApp
------------------------------------------------------
