[[установка-сервера-и-клиента]]
Установка сервера и клиента
---------------------------

Платформа Platypus поставляется в следующих вариантах:

* на компакт или DVD диске;
* через Интернет - в виде архивного файла в формате zip.

В случае поставки в виде архивного файла распакуйте его содержимое в
удобное для вас место на жестком диске.

_____________________________________________________________________________________________________________________________
*Note*

Инструкции по установке инструмента разработчика Platypus Application
Designer смотри в документе "Руководство разработчика".
_____________________________________________________________________________________________________________________________

[[системные-требования-платформы-platypus]]
Системные требования платформы Platypus
---------------------------------------

Ниже указаны необходимые условия для запуска компонентов платформы на
компьютере:

* 32-разрядный (x86) или 64-разрядный (x64) процессор с тактовой
частотой 1 гигагерц (ГГц) или выше;
* 1 гигабайт (ГБ) (для 32-разрядной системы) или 2 ГБ (для 64-разрядной
системы) оперативной памяти (ОЗУ);
* 5 гигабайт (ГБ) свободного пространства на жестком диске;
* операционная система Windows, Linux, Mac OS X или другая Unix
подобная;
* Oracle JRE 7 или OpenJDK 7;
* графический интерфейс пользователя для работы клиента;
* доступ к Интернет для получения обновлений и работы с внешним
картографическим сервисом. В корпоративной сети такой доступ может быть
организован через прокси-сервер;
* Web-браузер Google Chrome 19, Mozilla Firefox 10, Internet Explorer 9
или их более новые версии для работы HTML5 клиента Platypus.

Для работы приложений Platypus обычно необходим сервер баз данных (БД),
который может быть установлен как на том же компьютере что и клиент или
сервер приложений, так и на другом компьютере, доступном по сети.

Платформа Platypus поддерживает работу со следующими базами данных:

* Oracle Database 10g и выше;
* IBM DB2 9 и выше;
* Microsoft SQL Server 2008 и выше;
* MySQL (InnoDB) 5.5 и выше;
* PostgreSQL 9 и выше;
* H2 Database 1.3 и выше.

Для получения информации об установке и настройке сервера баз данных
обратитесь к соответствующим руководствам по установке и
администрированию, предоставляемым производителями серверов БД.

_____________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

В комплект поставки Platypus Platform включена база данных H2.
Использование данной БД доступно "из коробки" после установки платформы
и не требует дополнительных действий по установке и настройке.
_____________________________________________________________________________________________________________________________________________________________________________________________________

Для работы серверной части приложений внутри сервлет-контейнера или J2EE
сервера установите или используйте уже установленный сервлет-контейнер
или J2EE сервер. Работа Platypus тестировалась в следующем окружении:

* Apache Tomcat 7;
* Glassfish 3.1.2;
* JBoss AS7.

Для получения информации об установке и настройке сервлет-контейнера или
J2EE сервера обратитесь к соответствующим руководствам по установке и
администрированию, предоставляемым их производителями.

[[установка-платформы-platypus]]
Установка платформы Platypus
----------------------------

Для того, чтобы установить компоненты Платформы выполните следующие
действия:

1.  перейдите в подкаталог `install` дистрибутива Platypus;
2.  запустите файлы `install.bat` для операционной системы Windows или
выполните команду `sh install.sh` для Linux;
3.  выберите язык интерфейса пользователя программы по установке;
4.  выберите каталог установки;
5.  выберите компоненты которые будут установлены;
* Platypus Platform — ядро платформы Platypus;
* Java SE клиент;
* модули работы с картами;
* сервер приложений — включает в себя модули необходимые для работы
автономного сервера приложений и серверных компонентов в J2EE сервлет
контейнерах и серверах приложений;
* Platypus Communications - модули, необходимые для работы с COM/DCOM и
OPC серверами;
6.  выберите параметры настройки ярлыков для запуска клиента Platypus в
вашей системе.

__________________________________________________________________________________
*Note*

Компоненты ядра платформы являются обязательными при установке любой
конфигурации.
__________________________________________________________________________________

После установки, каталог будет иметь следующую структуру:

* `platypus/`
** `bin/`
** `lib/`
** `etc/`
** `run/`
** `logs/`

[[удаление-платформы-platypus]]
Удаление платформы Platypus
---------------------------

Для того, чтобы удалить платформу Platypus с компьютера выполните
следующие действия:

1.  запустите программу UninstallPlatypus из меню установленных программ
или с помощью ярлыка. Для ОС Windows используйте штатный механизм
удаления программ;
2.  подтвердите удаление компонентов Platypus, при необходимости
активируйте опцию удаления рабочего каталога.
