[[безопасность-в-platypus]]
Безопасность в Platypus
-----------------------

Платформа Platypus имеет развитые механизмы обеспечения безопасности и
обеспечивает ограничение доступа к ресурсам в системе на основе ролей
назначенных пользователям и их группам. Могут вводится ограничения
доступа к следующим ресурсам:

* Программный модуль любого уровня — на сервере или клиенте
* Функция в программном модуле
* Форма;
* Зпрос к базе данных
* Отчет

Разграничения на доступ к ресурсам осуществляются на базе ролей. Роли
вводятся на уровне приложения Platypus и являются его частью.

Для элемента приложения типа _Запрос к базе данных_ могут определяться
правила доступа для роли: полный доступ, только чтение (выполнение
запросов `SELECT`), запись (выполнение команд `INSERT`, `DELETE` и
`UPDATE`).

С точки зрения аутентификации, Platypus может использовать "область
безопасности". Область безопасности может быть встроенной или внешней и
содержать информацию о пользователях и об их принадлежности к группам.
Platypus поддерживает следующие варианты области безопасности:

* встроенная "база данных" пользователей, размещаемая в 2х таблицах БД —
может использоваться при работе как по 2-х так и 3-х звенной схеме;
* внешние хранилища аутентификационных данных, например, сервер LDAP
(Active Directory, OpenLDAP и т.д.), данный режим может использоваться
только при работе по 3-х звенной схеме в сервлет-контейнере или J2EE
сервере.

В области безопасности для пользователя определяется набор "групп" или
"глобальных ролей" которым могут быть поставлены в соответствие роли на
уровне приложения.

[[настройка-безопасности-при-работе-в-j2ee-контейнере]]
Настройка безопасности при работе в J2EE контейнере
---------------------------------------------------

При работе приложения в J2EE контейнере Platypus использует механизм
аутентификации и роли предоставляемые J2EE контейнером. Для активизации
ролевого доступа в данном случае необходимо чтобы пользователь прошел
ограничение безопасности и получил какую-либо роль. Для этого настройте
ограничение безопасности на URL на страницу на которой размещаются формы
Platypus для которых необходимо обеспечить контоль доступа на базе
ролей. На приведенном ниже примере включено ограничение безопасности для
страницы `applicationStart.html`, для доступа на которую пользватель
должен обладать любой ролью:

-----------------------------------------------------------
...
<security-constraint>
  <web-resource-collection>
      <url-pattern>/application-start.html</url-pattern>
    </web-resource-collection>
    <auth-constraint>
      <role-name>*</role-name>
    </auth-constraint>
</security-constraint>
<login-config>
    <auth-method>FORM</auth-method>
    <form-login-config>
      <form-login-page>/login.html</form-login-page>
      <form-error-page>/login-failed.html</form-error-page>
    </form-login-config>
</login-config>
<security-role>
    <role-name>*</role-name>
</security-role>
...
-----------------------------------------------------------

Укажите тип аутентификации, например `FORM` для аутентифифкации при
помощи HTML форм или `BASIC` для базовой аутентификации в соответсвии с
RFC 2617.

Platypus Client поддерживает `BASIC` аутентификацию, поэтому для его
корректной работы должен быть настроен именно этот тип аутентификаци.

Настройте хранилище информации о пользователях и J2EE контейнер для
использвания этого хранилища, более подробная информация об этих
настойках представлена ниже.

При работе приложения в J2EE контейнере в добавлении к ограничениям
безопасности платфомы Platypus необходимо использвать встроенные
средства web-сервера:

* ограничте доступ к файлам приложения по протоколу HTTP;
* ограничте доступ к файлам приложения для загрузчика ресурсов Platypus,
работающего по URL вида:
+
application/resource/
+
где resourcePath — путь к ресурсу в приложении Platypus.

Настройте разграничения доступа в файле дескриптора `WEB-INF/web.xml`.

В приведенном ниже примере показан фрагмент файла `WEB-INF/web.xml` в
котором ограничивается доступ к файлам приложения Platypus, размещенного
в каталоге `app`, за исключением подкаталога `public`:

--------------------------------------------------------
...
<security-constraint>
  <web-resource-collection>
      <!-- whitelist -->
      <web-resource-name />
      <url-pattern>/app/public/*</url-pattern>
      <url-pattern>/application/resource/public/*
      </url-pattern>
   </web-resource-collection>
   <!-- No auth constraint here for whitelist -->
</security-constraint>

<security-constraint>
  <web-resource-collection>
      <!-- everything other is restricted -->
      <web-resource-name />
      <url-pattern>/app/*</url-pattern>
      <url-pattern>/application/resource/*</url-pattern>
  </web-resource-collection>
  <auth-constraint />
</security-constraint>
...
--------------------------------------------------------

[[настройка-прав-доступа-пользователей-при-использовании-встроенного-хранилища-информации-о-пользователях]]
Настройка прав доступа пользователей при использовании встроенного
хранилища информации о пользователях
-------------------------------------------------------------------------------------------------------

Использование встроенного хранилища предоставляет простые инструменты
для хранения информации о пользователях и их группах.

Данный режим является единственным возможным режимом при работе в 2-х
звенной схеме и работе по 3-х звенной схеме в варианте работы сервера
приложений Platypus вне J2EE сервера, а также может быть сконфигурирован
при работе Platypus в составе J2ЕЕ сервера. Для использования этого
режима в сервлет контейнере или в J2EE сервере должна быть настроена
соответствующая область безопасности - Security Realm.

_____________________________________________________________________________________________________________________________________________
*Note*

Справочную информацию по настройке области безопасности для сервера
Glassfish смотрите в приложении B: "Настройка области безопасности
LDAP".

Справочную информацию по настройке области безопасности для Apache
Tomcat смотрите в документации на сервлет-контейнер Tomcat.
_____________________________________________________________________________________________________________________________________________

В данном режиме информация о пользователях хранится в базе данных
приложения в таблице `MTD_USERS`. Каждая запись в этой таблице
соответствует одному пользователю. Сведения о группах, к которым
принадлежит пользователь хранятся в таблице `MTD_GROUPS`. Каждому
пользователю может быть сопоставлено 0 и более групп.

Таблица `MTD_USERS` содержит следующие обязательные поля:

[cols="<,<",options="header",]
|=======================================================================
|Поле |Описание
|`USR_NAME` |Имя пользователя

|`USR_PASSWD` |Хэш-сумма пароля пользователя, с использованием алгоритма
MD5

|`USR_FORM` |Идентификатор формы по умолчанию, например
`comAppFormsWelcome`
|=======================================================================

Кроме того, таблица `MTD_USERS` может содержать необязательные поля,
содержащие дополнительную информацию о пользователе.

Таблица `MTD_GROUPS` содержит следующие обязательные поля:

[cols="<,<",options="header",]
|============================
|Поле |Описание
|`USR_NAME` |Имя пользователя
|`GROUP_NAME` |Имя группы
|============================

Для разработки и тестирования приложений используйте технический логин
`admin` c паролем `masterkey`. Пользователь `admin` включен в группу
`admin`.

_______________________________________________________________________________
*Important*

Измените технический пароль перед началом промышленной эксплуатации
приложения!
_______________________________________________________________________________

[[использование-внешнего-хранилища-информации-о-пользователях]]
Использование внешнего хранилища информации о пользователях
-----------------------------------------------------------

Данный режим дает возможность использования внешних сервисов для
аутентификации пользователя, например OpenLDAP или Microsoft Active
Directory.

С этим режимом аутентификации могут работать Platypus Web API клиенты,
HTML5 браузерный клиент и Java SE Platypus клиент при соединении с
сервлет контейнером или J2EE сервером по протоколам HTTP/HTTPS. Для
использования этого режима в сервлет контейнере или в J2EE сервере
должна быть настроена соответствующая область безопасности - Security
Realm.

_____________________________________________________________________________________________________________________________________________
*Note*

Справочную информацию по настройке области безопасности для сервера
Glassfish смотрите в приложении B: "Настройка области безопасности
LDAP".

Справочную информацию по настройке области безопасности для Apache
Tomcat смотрите в документации на сервлет-контейнер Tomcat.
_____________________________________________________________________________________________________________________________________________
