[[конфигурирование-и-запуск-сервера-приложений-platypus]]
Конфигурирование и запуск сервера приложений Platypus
-----------------------------------------------------

Сервер приложений Platypus Application Server предназначен для
централизованного выполнения бизнес-логики и является промежуточным
слоем при работе Platypus по 3-х звенной схеме.

Сервер приложений может быть развернут автономно или внутри
сервелет-контейнера/J2EE сервера.

3-х звенная схема имеет ряд преимуществ по сравнению с 2-х звенной:

* лучшая безопасность в следствии того, что у клиента нет прямого
доступа к базе данных и по сети не передается текст запросов к БД;
* лучшая производительность из-за того что бизнес-логика выполняется на
сервере;
* лучшая сопровождаемость системы;
* масштабируемость конечного приложения;
* возможность использовать HTML5 web-браузер в качестве клиента (с
использванием J2EE сервлет-контейнера/сервера приложений).

[[запуск-сервера-приложений-platypus]]
Запуск сервера приложений Platypus
----------------------------------

В данном режиме сервер приложений Platypus запускается в собственном
процессе и собственной виртуальной машине Java (JVM) .

Для запуска сервера приложений Platypus необходимо запустить стартовый
скрипт.

Скрипт запуска сервера Platypus находятся в папке `/run` :

* `server.bat` — для запуска сервера в ОС Windows;
* `server.sh` — для запуска сервера в ОС Linux.

Для промышленной эксплуатации сервера приложений Platypus рекомендуется
настроить его запуск в качестве службы ОС.

[[настройка-скрипта-и-параметры-командной-строки-запуска-сервера-приложений-platypus]]
Настройка скрипта и параметры командной строки запуска сервера
приложений Platypus
----------------------------------------------------------------------------------

Данный раздел содержит подробную справочную информацию по параметрам
командной строки запуска сервера приложений Platypus.

Для настройки запуска сервера Platypus отредактируйте содержимое файлов
скрипта запуска. Могут быть настроены следующие параметры:

* путь к приложению Platypus, в этом случае параметры соединения с БД
будут получены из конфигурационного файла;
* параметры соединения с БД;
* сетевые интерфейсы и протоколы;
* модули обработки входящих данных и фоновых задач;
* уровень логов и файл записи логов.

Для настройки отредактируйте переменные и параметры строки запуска
скрипта.

Команда для запуска клиента имеет следующий вид:

-----------------------------------------------
java -cp Server.jar; com.eas.server.ServerMain 
-----------------------------------------------

где EXT_CLASSPATH - пути, которые должны быть добавлены в путь поиска
загрузчика классов Java, OPTIONS - дополнительные параметры запуска.

Так же сервер приложений можно запустить с использованием параметра
`-jar`:

---------------------
java -jar Server.jar 
---------------------

Такой вариант запуска удобен, при работе с командной строкой, однако
такой подход не позволяет добавлять внешние библиотеки в путь по
которому загрузчик Java ищет классы. Например, библиотеки отвечающие за
соединение с нетиповыми базами данных или компоненты сторонних
производителей, используемые конечным приложением в процессе обработки
бизнес-логики.

.Параметры запуска сервера приложений из командной строки
[cols="<,<",options="header",]
|=======================================================================
|Параметр |Описание
|`applicationpath APP_PATH` |Путь к папке, содержащей приложение. Если
задан этот параметр, то приложение будет запущено с диска из этой папки,
в противном случае приложение будет запущено из базы данных. Этот
параметр имеет короткий синоним ap

|`-url JDBC_URL` |URL соеденения с БД в формате JDBC.

|`-dbuser DB_USER` |Имя пользователя для авторизации в БД.

|`-dbpassword DB_PASSWORD` |Пароль пользователя для авторизации в БД.

|`-dbschema DB_SCHEMA` |Схема БД.

|`-iface`ADRESS:PORT,ADRESS:PORT |Сетевые интерфейсы и порты
прослушивания для сервера.

|`-protocols` PORT:PROTOCOL,PORT:PROTOCOL |Сетевые протоколы для портов
прослушивания.

|`-loglevel LOG_LEVEL` |Уровень ведения журнала. Данный параметр
указывает минимальный уровень который будет выводится в журнал. Описание
уровней журнала смотрите в Приложении A.

|`-log LOG_FILE_PATH` |Имя и путь к файлу журнала.

|`-tasks` MODULES_NAME |Список серверных модулей (через запятую без
пробелов) для обработки входящих данных и фоновых задач. У модуля
обработки входящих данных должна быть определена функция received(data).
Модули обработки входящих данных могут быть как с аннотацией @stateless,
так и без нее. У модулей фоновых задач не должно быть аннотации
@stateless. При старте сервера, модули с этой аннотацией будут
пропущены.
|=======================================================================

Пример команды запуска сервера приложений Platypus:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
java -cp Server.jar com.eas.server.ServerMain -url jdbc:oracle:thin:@serverHost:1521:adb -dbuser user1 -dbpassword secret -loglevel INFO -log serverlog.log -iface 0.0.0.0:8500 -protocols 8500:platypus
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Пример команды запуска сервера приложений с использованием параметра
`-jar`:

-----------------------------------------------------------------------------------------------------------------------------------------------------
java -jar Server.jar -ap ~/apps/testApp -url jdbc:oracle:thin:@serverHost:1521:adb -dbuser user1 -dbpassword secret -loglevel INFO -log serverlog.log
-----------------------------------------------------------------------------------------------------------------------------------------------------
