[[диаграмма-структуры-базы-данных]]
Диаграмма структуры базы данных
-------------------------------

_Диаграмма структуры базы данных_ является представлением структуры БД в
части, определенной разработчком. Например, диаграмма может описывать
часть предметной области. В проекте, как правило, существует несколько
диаграмм структуры БД.

Диаграмма структуры БД является визуальным представлением структуры БД и
на прямую не влияет на функциональность приложения.

Структура реляционной базы данных определяется составом таблиц и их
связями. Связи между двумя таблицами реализуются через внешние ключи.

_________________________________________________________________________________________________________________
*Note*

Подробное описание понятий "таблица", "внешний ключ", "сущность" и пр.
см литературу по реляционным базам данных.
_________________________________________________________________________________________________________________

[[создание-новой-диаграммы-структуры-бд]]
Создание новой диаграммы структуры БД
-------------------------------------

Для создания новой диаграммы структуры базы данных выполните следующие
действия:

* выберите пункт меню New контекстного меню родительского каталога или
выделите родительский каталог и выберите пункт New Filе главного меню
или нажмите кнопку New File на панели инструментов или воспользуйтесь
"горячей" клавишей;
* выберите тип Database structure diagram из контекстного меню или на
первом шаге мастера Choose file type Platypus application elements
Database structure diagram и нажмите Next;
* выберите соединение с БД и схему БД:
** выберите базу данных по-умолчанию — нажмите кнопку Default или
подключение к внешней базе данных — нажмите кнопку Specific;
** выберите схему в базе данных из выпадающего списка поля Schema; для
выбора схемы по умолчанию нажмите кнопку Default;
** нажмите кнопку Next;
* введите название новой диаграммы структуры БД в поле Name и нажмите
Finish для создания нового элемента приложения или Cancel для отмены.

После создания диаграммы структуры БД сформируйте структуры таблиц. Для
этого определите состав полей и задайте их описание. После определения
структуры таблиц определите связи между таблицами.

[[редактирование-диаграммы-структуры-бд]]
Редактирование диаграммы структуры БД
-------------------------------------

Редактирование диаграммы структуры базы данных осуществляется при помощи
специализированного редактора.

Диаграмма БД представляет из себя визуальное представление таблиц базы,
а также связей между ними. Одна диаграмма обычно включает в себя часть
общей структуры базы, например, относящиеся к определенному сегменту
предметной области. При помощи визуального редактора осуществляется
изменение структуры базы данных — добавление и удаление таблиц, связей
между таблицами и индексов. Одна и та же таблица может быть представлена
на нескольких диаграммах.

Для навигации по диаграмме удобно использовать инспектор диаграммы. В
инспекторе диаграммы таблицы и их поля представлены в виде дерева. При
выделении таблицы или поля в инспекторе, происходит такое же выделение
на диаграмме. Кроме того, имеется возможность взаимного позиционирования
инспектора и диаграммы.

Для того, чтобы взаимно спозиционировать узел в инспекторе и объект на
диаграмме выберите пункт меню Show in diagram в контектсном меню узла
таблицы.

Для добавления на диаграмму существующей таблицы выполните следующие
действия:

* выберите пункт меню Add table - на панели инструментов редактора или
воспользуйтесь "горячей" клавишей Ctrl Shift Insert;
* выберите таблицу из списка в диалоге выбора таблицы, при необходимости
воспользуйтесь поиском, нажав на кнопку Find;
* нажмите кнопку OK для добавления таблицы или Cancel для отмены;
* при необходимости передвиньте таблицу на диаграмме в нужное место;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для создания новой таблицы и добавления её на диаграмму выполните
следующие действия:

* выберите пункт меню Add table Create new table на панели инструментов
редактора;
* введите имя новой таблицы в диалоге;
* нажмите кнопку OK для добавления таблицы или Cancel для отмены;
* при необходимости передвиньте таблицу на диаграмме в нужное место;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

__________________________________________________________________________________________________________
*Note*

Для новой таблицы будет автоматически создано числовое поле
идентификатора и ограничение первичного ключа.
__________________________________________________________________________________________________________

Для удаления таблицы из диаграммы выполните следующие действия:

* выберите таблицу на диаграмме;
* нажмите кнопку Delete на панели инструментов редактора;
* на диалоге подтверждения удаления нажимите кнопку Delete from diagram
для того, чтобы удалить таблицу из диаграммы (только из диаграммы, а не
из БД) кнопку Drop table для того, чтобы удалить таблицу из базы данных
(при этом таблица будет уничтожена физически) или кноку Cancel для
отмены удаления;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для того, чтобы добавить поля таблицы:

* выберите таблицу на диаграмме;
* нажмите кнопку Create new field/parameter на панели инструментов
вкладки редактора полей таблицы — будет создано поле с типом по
умолчанию и автоматически сгенерированным именем;
* измените свойства поля таблицы, для этого выберети узел поля среди
дочерних узлов таблицы в инспекторе модели данных и измените свойства в
окне редактирования свойств Properties:

Свойства поля таблицы:

* Name — наименование поля в таблице;
* Description — описание поля;
* Type — тип данных;
* Type Name — имя типа структуры данных, поле доступно для ввода если
выбран тип данных `STRUCT`;
* Size — длина поля;
* Scale — масштаб;
* Nullable — необязательное поле (в поле допустимы значения `NULL)`;

[cols="<,<",options="header",]
|============================================
|Наименование типа |Описание
|`NUMERIC` |Число
|`VARCHAR` |Строка ограниченной длины
|`TIMESTAMP` |Дата и время
|`DATE` |Дата
|`STRUCT` |Структура
|`BLOB` |Двоичные данные неограниченной длины
|`CLOB` |Строка неограниченной длины
|============================================

Для редактирования поля выполните следующие действия:

* выберите узел поля среди дочерних узлов таблицы в инспекторе модели
данных;
* отредактируйте параметры поля в окне редактора свойств Properties;

_____________________________________________________________________________
*Important*

Не используйте для полей таблиц следующие имена: `md`, `params`.

Эти имена являются зарезервированными и используются моделью данных
Platypus.
_____________________________________________________________________________

____________________________________________________________________________________________________________________________________________________________
*Note*

Если панель свойств Properties не отображается, включите эту панель —
для этого выберите пункт Window Properties главного менюPlatypus
Application Designer.
____________________________________________________________________________________________________________________________________________________________

Для удаления поля выполните следующие действия:

* выберите поле в таблице на диаграмме;
* нажмите кнопку Delete на панели инструментов редактора полей или
нажмите сочетание клавиш Ctrl Delete;

Для того, чтобы редактировать индексы таблицы, используйте инспектор:
раскройте узел соответсвующей таблицы, и используйте узел Indexes.

Для того, чтобы добавить новый индекс:

* выберите пункт меню Add index контекстного меню узла Indexes
соответсвующей таблицы;
* в диалоге выбора колонок таблицы выберите необходимые поля и нажмите
кнопку для добавления OK или Cancel для отмены;
* при необходимости удалите поле из индекса используя пункт Delete
контекстного меню колонки индекса;
* при необходимости измените порядок полей в индексе используя пункты
Move up и Move down контекстного меню колонки индекса;
* при необходимости измените состояние флажка Ascending на панели
свойств для колонки индекса, задав порядок сортировки по возрастанию или
убыванию;
* задайте имя индекса в поле Index name на панели свойств узла индекса;
* при необходимости установите флажок Unique на панели свойств узла
индекса, чтобы сделать индекс уникальным или не уникальным;
* при необходимости установите флажок Clustered на панели свойств узла
индекса, чтобы сделать индекс кластерным;
* при необходимости установите флажок Hashed на панели свойств узла
индекса, чтобы включить или выключить хеширование для этого индекса.

Для того, чтобы изменить индекс:

* выберите индекс в списке индексов таблицы;
* отредактируйте индекс аналогично действиям по добавлению нового
индекса;

Для того, чтобы удалить индекс:

* выберите индекс среди дочерних узлов соответствующей таблицы в
инспекторе;
* выберите пункт меню Delete контекстного меню узла индекса.

Для того, чтобы добавить внешний ключ таблицы:

* перетащите мышкой поле одной таблицы на поле-первичный ключ другой
таблицы;
+
после этого в базе данных будет создан внешний ключ; визуально связь
будет представлена линией со стрелкой между полями таблиц;
+
_______________________________________________________________________________________________________________________________________________________________________________________________
*Important*

Типы полей, связанные внешним ключом, должны быть одинаковыми. Для
создания древовидной структуры (унарной связи) перетащите мышкой поле
таблицы на поле - первичный ключ той же самой таблицы;
_______________________________________________________________________________________________________________________________________________________________________________________________
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для того, чтобы удалить внешний ключ таблицы:

* выделите связь внешнего ключа мышью;
* нажмите кнопку Delete или используйте комбинацию клавиш Ctrl Delete:
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

При работе в команде разработчиков после изменения структуры БД
рекомендуется создать миграцию - мгновенный снимок метаданных и сделать
его доступным другим участникам процесса разработки, для того, чтобы
применить сделанные изменения на других экземплярах баз, участвующих в
разработке.
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Для того, чтобы выполнить запрос данных из таблицы:

* перейдите на вкладку Database schema;
* выберите таблицу на диаграмме;
* нажмите кнопку Query Table Data — будет выполнен запрос данных из
таблицы, а результаты будут показаны в зоне вывода редактора.

Для того, чтобы изменить размер визуального представления диаграммы
структуры БД:

* перейдите на вкладку Database schema;
* нажмите кнопку Zoom In для того, чтобы увеличить, и кнопку Zoom out
для того, чтобы уменьшить представление структуры БД в редакторе.

Для того, чтобы воспользоваться поиском по диаграмме:

* перейдите на вкладку Database schema;
* нажмите кнопку Find для того, чтобы открыть диалог поиска по
диаграмме;
* введите строку поиска;
* выберите поля по которым будет осуществляются поиск: Datasets, Fields,
Params, а также установите флажки опций: Whole words — для поиска целых
слов, Match case — для поиска с учетом регистра символов;
* нажмите кнопки Next и Previous для перехода к следующей найденной
сущности;
* нажмите кнопку Close чтобы закрыть диалог поиска.
