[[подключение-к-внешней-базе-данных]]
Подключение к внешней базе данных
---------------------------------

Каждое приложение платформы Platypus имеет соединение с базой данных по
умолчанию, которое задается при создании приложения. Кроме того,
приложение может использовать соединения с произвольным количеством
внешних баз данных.

Для определения соединения с внешними базами данных используются
элементы приложения типа _Подключение к внешней базе данных_.

[[создание-нового-подключения-к-внешней-бд]]
Создание нового подключения к внешней БД
----------------------------------------

Для создания нового подключения к внешней БД выполните следующие
действия:

* выберите пункт меню New контекстного меню родительского каталога или
выделите родительский каталог и выберите пункт New Filе главного меню
или нажмите кнопку New File на панели инструментов или воспользуйтесь
"горячей" клавишей;
* выберите тип External database connection из контекстного меню или на
первом шаге мастера Choose file type Platypus application elements
External database connection - и нажмите Next;
* введите название нового элемента приложения в поле Name и нажмите
Finish для его создания или Cancel для отмены.

[[редактирование-подключения-к-внешней-бд]]
Редактирование подключения к внешней БД
---------------------------------------

Редактирование элемента приложения типа _Подключения к внешней БД_
осуществляется при помощи специализированного редактора. Для открытия
редактора элемента приложения дважды кликните по элементу приложения в
дереве проекта.

Для изменения настроек подключения к внешней БД:

* заполните полe Name — имя-идентификатор элемента приложения соединения
с внешней БД; имя-идентификатор подчиняется требованиям к именам
элементов приложения Platypus;
* заполните полe JDBC Url — URL соединения с внешней БД в формате JDBC;
* заполните полe Database User — имя пользователя в БД;
* заполните полe Password — пароль пользователя в БД;
* Выберите схему по умолчанию для этого подключения из выпадающего
списка в поле Default schema;
* проверьте соединение с БД нажав кнопку Test connection;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

При работе приложения в среде J2EE сервера или сервлет-контейнера
соединение с базой данных предоставляется окружением, в котором работает
приложение Platypus. Настройте соединение с базой данных как JNDI-ресурс
и укажите имя этого ресурса в поле JDBCURL. Поля Database User, Password
и Default schema в этом случае не заполняются и тестирование соединения
не производится.
