[[установка-и-настройка-platypus-application-designer]]
Установка и настройка Platypus Application Designer
---------------------------------------------------

В данном разделе содержится информация по установке основного средства
разработки приложений на платформе Platypus — Platypus Application
Designer.

Программное обеспечение дизайнера приложений входит в комплект
разработчика и поставляется совместно с платформой Platypus.

Комплект разработчика Platypus поставляется в следующих вариантах:

* на компакт или DVD диске;
* через Интернет — в виде архивного файла в формате zip.

В случае поставки комплекта разработчика в виде архивного файла
распакуйте его содержимое в удобное для вас место на жестком диске.

_____________________________________________________________________________________________
*Note*

Инструкции по установке платформы Platypus смотрите в документе
"Руководство администратора".
_____________________________________________________________________________________________

[[системные-требования-для-установки-дизайнера-приложений]]
Системные требования для установки дизайнера приложений
-------------------------------------------------------

Системные требования для установки комплекта разработчика на компьютере
включают минимальные системные требования к компьютеру для установки
исполняемой части платформы Platypus со следующими уточнениями:

* 32-разрядный (x86) или 64-разрядный (x64) процессор с тактовой
частотой 1 гигагерц (ГГц) или выше;
* 2 гигабайта (ГБ) (для 32-разрядной системы) или 3 ГБ (для 64-разрядной
системы) оперативной памяти (ОЗУ);
* 10 гигабайт (ГБ) свободного пространства на жестком диске;
* операционная система с графическим интерфейсом пользователя;
* Oracle JDK 7;
* доступ к Интернет для получения обновлений.

[[установка-дизайнера-приложений]]
Установка дизайнера приложений
------------------------------

Для того, чтобы установить комплект разработчика выполните следующие
действия:

1.  установите платформу Platypus;
2.  перейдите в подкаталог `designer` дистрибутива комплекта
разработчика Platypus;
3.  запустите файлы `platypusdesigner-windows.exe` для операционной
системы Windows или `platypusdesigner-linux.sh` для Linux;
+
_____________________________________________________________________________________________
*Note*

Для ОС Linux пользователь должен иметь права доступа, позволяющие
запустить исполняемый файл.
_____________________________________________________________________________________________
4.  нажмите кнопку Next для перехода к следующему шагу процесса
установки;
5.  прочитайте условия лицензирования программного обеспечения и для их
принятия установите флажок I accept the terms of the license agreement;
Нажмите кнопку Next для перехода к следующему шагу процесса установки;
6.  выберите каталог установки приложений и опции по созданию ярлыков на
Рабочем столе и пунктов в меню установленных программ; нажмите кнопку
Next для перехода к следующему шагу процесса установки;
7.  нажмите кнопку Install для начала установки Platypus Application
Designer;
8.  после окончания установки нажмите кнопку Finish; установите флажок
Launch Platypus application designer after the installer closes для
немедленного запуска дизайнера.

_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

Укажите путь к JDK в параметре `jdkhome` в файле конфигурации Platypus
Application Designer, находящегося в
`platypusdesigner/etc/platypusdesigner.conf` в случае, если JDK
установлен в место на жестком диске отличное от места по умолчанию.
Неправильное значение параметра jdkhome может приводить к ошибкам при
запуске приложения.
_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

[[настройка-запуска-дизайнера-приложений]]
Настройка запуска дизайнера приложений
--------------------------------------

Platypus Application Designer поддерживает локализацию текстов меню,
сообщений и т.д. В настоящее время реализована поддержка для следующих
языков:

* английский язык;
* русский язык.

Язык локализации выбирается автоматически при запуске приложения
дизайнера в соответствии с региональными настройками пользователя в
операционной системе.

Для того, чтобы принудительно изменить язык локализации:

* отредактируйте файл конфигурации Platypus Application Designer —
добавьте в параметр `default_options` опцию `--locale ru:RU` или
`--locale en:US`;
* перезапустите дизайнер приложений.

Вы также можете изменить язык локализации дизайнера добавив опцию
-`-locale ru:RU` или `--locale en:US` в строку команды на запуск
Platypus Application Designer.

Дизайнер Platypus поддерживает подключение различных стилей оформления
пользовательского интерфейса (LaF — Look and Feel). Существуют стили
оформления для конкретной операционной системы, универсальные стили
(`Metal` и `Nimbus`) и стили оформления которые могут поставляться
сторонними разработчиками.

_______________________________________________________________________________________________________________
*Warning*

Подключение внешних стилей оформления является достаточно сложной
процедурой и не рекомендовано для начинающих.
_______________________________________________________________________________________________________________

Для того, чтобы изменить стиль оформления Platypus Application Designer:

* отредактируйте файл конфигурации дизайнера — добавьте в параметр
`default_options` опцию `--laf`, где LaF соответствует названию стиля
или полному имени класса LaF, в случае использования стороннего LaF
также необходимо включить библиотеку стилей в путь доступный загрузчику
классов Platypus Application Designer;
* перезапустите дизайнер приложений.

[[настройка-среды-разработки-дизайнера-приложений]]
Настройка среды разработки дизайнера приложений
-----------------------------------------------

Укажите место в файловой системе компьютера, где находится каталог
Platypus Platform:

* выберите пункт главного меню Tools Platypus Platform;
* в диалоге выбора задайте путь к каталогу размещения Platypus Platform.

Добавьте экземпляр J2EE сервера, который может быть использован для
запуска приложения Platypus:

* в окне Services в контекстном меню узла Servers выберите пункт Add
server...;
* в мастере добавления J2EE сервера выберите тип сервера, его имя и
задайте его настройки: путь к каталогу сервера, логин и пароль
администратора.

_______________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

В текущей версии PlatypusApplication Designer поддерживается запуск
приложений в Apache Tomcat 7. Скачайте Apache Tomcat 7 с сайта
разработчика и установите (распакуйте) его в удобное для вас место на
жестком диске.
_______________________________________________________________________________________________________________________________________________________________________________________________________________________

[[удаление-дизайнера-приложений]]
Удаление дизайнера приложений
-----------------------------

Для того, чтобы удалить дизайнер приложений Platypus с компьютера
выполните следующие действия:

1.  запустите приложение Uninstall Platypus Application Designer из меню
установленных программ. Для ОС Windows используйте штатный механизм
удаления программ, в качестве альтернативного варианта для удаления
воспользуйтесь программой `uninstall.exe` для OC Windows или
`uninstall.sh` для ОС Linux из каталога в который был установлен
Platypus Application Designer;
2.  подтвердите удаление приложений и компонентов Platypus нажав кнопу
Finish, при необходимости активируйте опцию удаления конфигурационных
данных из каталога пользователя.
