[[запрос-к-базе-данных]]
Запрос к базе данных
--------------------

_Запрос_ в Platypus — это элемент приложения, определяющий SQL выражение
для выполнения в базе данных. В платформе Platypus запрос подвергается
предварительной обработке перед выполнением.

Запросы решают несколько задач:

* формулируют задания на выборку данных из БД (запросы типа `SELECT`);
* определяют метаданные для обработки результатов выборки (запросы типа
`SELECT`);
* определяют метаданные для обработки изменений в данных, сделанных в
процессе работы приложения (запросы типа `SELECT`);
* формулируют задания добавления и обновления данных в БД (запросы типа
`INSERT`, `DELETE` и `UPDATE`).

_________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

Задачи добавления и обновления данных в большинстве случаев могут быть
решены моделью данных автоматически в процессе сохранения изменений. Для
этого достаточно определить запрос типа `SELECT`.
_________________________________________________________________________________________________________________________________________________________________________________________________

Запросы в платформе Platypus имеют следующие особенности:

* запросы поддерживают именованные параметры предопределенного типа;
* реализовано повторное использование — включение одних запросов в
другие без копирования их тела;
* редактирование запросов в визуальной форме и в виде текста
одновременно;
* результаты выполнения запроса транслируются в сущности, пригодные для
обработки JavaScript кодом, этим занимается JavaScript ORM платформы
Platypus;
* с помощью запроса можно задать характер обработки изменений в данных,
сделанных в процессе работы приложения: можно задать перечень таблиц, в
которые будут сохраняться изменения, а также разрешить или запретить
сохранение изменений для сущностей, полученных из БД с помощью этого
запроса.

[[создание-нового-запроса-к-базе-данных]]
Создание нового запроса к базе данных
-------------------------------------

Для создания нового запроса выполните следующие действия:

* выберите пункт меню New контекстного меню родительского каталога или
выделите родительский каталог и выберите пункт New Filе главного меню,
или нажмите кнопку New File на панели инструментов, или воспользуйтесь
"горячей" клавишей;
* выберите тип Query из контекстного меню или на первом шаге мастера
Choose file type Platypus application elements Query — и нажмите кнопку
Next;
* выберите соединения с БД и схему:
** выберите базу данных по умолчанию — нажмите кнопку Default или
подключение к внешней базе данных - нажмите кнопку Specific; выберите
элемент приложения типа Db Connection с помощью диалога выбора элемента
приложения;
** нажмите кнопку Next;
* введите название нового запроса в поле Name и нажмите кнопку Finish
для создания нового элемента приложения или Cancel для отмены.

После завершения работы мастера создания запроса будет создан новый
пустой запрос.

[[редактирование-запроса-к-базе-данных]]
Редактирование запроса к базе данных
------------------------------------

Операции по редактированию запроса осуществляются при помощи
специализированного редактора, позволяющего как визуальное
редактирование запроса, так и непосредственно редактирование SQL-текста.

_________________________________________________________________________________________________________________________________________________________________________________
*Important*

Полноценное редактирование с использованием визуального дизайнера
возможно при наличии соединения с базой данных. В отсутствии соединения
доступно лишь изменение текста запроса.
_________________________________________________________________________________________________________________________________________________________________________________

Для того, чтобы определить общие свойства, используйте панель свойств
запроса или вручную добавьте соответствующую аннотацию в заголовок
запроса:

* выберите в инспекторе запроса корневой узел;
* отредактируйте свойства запроса на панели Properties (при
необходимости активируйте ее в глобальном меню Windows Properties);
** установите флажок public, если запрос должен быть доступен на сервере
для вызова из Platypus Client или браузера — в заголовок запроса будет
добавлена аннотация `@public`;
** установите флажок procedure, если запрос будет использован для вызова
хранимой процедуры — в заголовок запроса будет добавлена аннотация
`@procedure`;
** установите флажок manual, если вы хотите избежать автоматического
исполнения этого запроса при его работе в составе модели данных модуля,
отчета или формы при их инициализации, например, если запрос содержит
вызов хранимой процедуры, выражения `INSERT` или `UPDATE` — в заголовок
запроса будет добавлена аннотация `@manual`;
** установите флажок readonly, если вы не хотите, чтобы изменения в
данных сущностей, полученных с помощью этого запроса, были сохранены в
БД;
** откройте диалог выбора подключения БД, которому назначен этот запрос,
нажав кнопку External db connection, и выберите элемент приложения типа
"Подключение к внешней БД" или введите имя элемента приложения данного
типа; для того, чтобы назначить запрос подключению к БД по умолчанию
очистите это поле.

Для навигации по элементам запроса удобно использовать инспектор
запроса. В инспекторе запроса параметры, таблицы и подзапросы
представлены в виде дерева, листьями которого являются параметры и поля
данных.

Выделить таблицу или подзапрос можно как в визуальном редакторе, так и в
инспекторе запроса.

Создание запроса можно начинать как с задания параметров запроса (если
это необходимо), так и с визуального дизайнера. Рассмотрим сначала
работу с визуальным дизайнером запроса.

Для добавления таблицы в запрос выполните следующие действия:

* выберите вкладку SQL designer редактора запросов;
* выберите пункт меню Add table / Add query Add table на панели
инструментов редактора или воспользуйтесь "горячей" клавишей Ctrl Shift
Insert;
* выберите таблицу из списка в диалоге выбора таблицы; при необходимости
выберите схему из выпадающего списка поля Schema; кнопка Default
устанавливает схему по умолчанию для приложения; воспользуйтесь поиском,
нажав на кнопку Find, если необходимо;
* нажмите кнопку OK для добавления таблицы или Cancel для отмены;
* при необходимости передвиньте таблицу на диаграмме запроса в нужное
место;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для включения существующего запроса в редактируемый запрос в качестве
подзапроса выполните следующие действия:

* выберите пункт меню Add table/Add query Add query на панели
инструментов редактора;
* выберите элемент приложения типа Query в диалоге выбора;
* нажмите кнопку OK для добавления запроса или Cancel для отмены;
* при необходимости передвиньте запрос на диаграмме визуального
редактора в нужное место;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

_____________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

Перетащите существующий запрос из дерева элементов приложения панели
проектов на диаграмму визуального редактора запроса для того, чтобы
включить его в редактируемый запрос, не открывая диалог выбора элементов
приложения.
_____________________________________________________________________________________________________________________________________________________________________________________________________________________________

Для назначения псевдонима таблицы или подзапроса выполните следующие
действия:

* перейдите на вкладку SQL designer;
* выберете на диаграмме запроса таблицу или подзапрос;
* на панели свойств Properties задайте значение в поле alias;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для удаления таблицы или подзапроса из диаграммы визуального дизайнера
запроса выполните следующие действия:

* выберите таблицу или подзапрос на диаграмме или в инспекторе запроса;
* нажмите кнопку Delete на панели инструментов редактора запросов для
того, чтобы удалить таблицу или подзапрос из диаграммы;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

____________________________________________________________________________________________________________________________________________________________
*Note*

Если панель свойств Properties не отображается, включите эту панель -
для этого выберите пункт Window Properties главного менюPlatypus
Application Designer.
____________________________________________________________________________________________________________________________________________________________

Для того, чтобы добавить параметры запроса:

* нажмите кнопку New field/parameter на панели инструментов вкладки
редактирования полей чтобы добавить поле;
* измените свойства нового параметра, для этого выберите его узел среди
узлов параметров запроса в инспекторе и отредактрируйте свойства
параметра в окне Properties;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Свойства поля параметра:

* Name — наименование параметра;
* Description — описание параметра;
* Type — тип параметра, выберите из выпадающего списка тип параметра;
* Type Name — имя типа структуры данных, поле доступно для ввода если
выбран тип поля Structure;
* Size — длина или точность поля;
* Mode — установите данное поле если параметр будет использован в
качестве параметра хранимой процедуры.

Режимы использования параметра в вызовах хранимых процедур:

[cols="<,<",options="header",]
|============================================
|Значение |Описание
|`in` |Режим работы `IN`
|`in/out` |Режим работы `IN/OUT`
|`out` |Режим работы `OUT`
|`unknown` |Режим работы параметра неизвестен
|============================================

Для редактирования параметра запроса выполните следующие действия:

* выберите узел параметра среди узлов параметров в инспекторе;
* отредактируйте параметры аналогично действиям при создании нового
параметра;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для удаления параметра выполните следующие действия:

* выберите параметр на панели параметров;
* нажмите кнопку Delete на панели инструментов вкладки редактирования
параметров или нажмите сочетание клавиш Ctrl Delete;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Параметр запроса может быть связан с полем таблицы или подзапроса или
быть связанным с параметром подзапроса.

При связи с полем параметр будет включен в текст SQL — визуально связь
будет отображаться как черная линия со стрелкой.

При связи параметра с параметром подзапроса для данной связи будет
создано сопоставление параметров в модели запроса — визуально такая
связь будет отображаться как пурпурная линия со стрелкой.

Для того, чтобы добавить связь параметра и поля или параметра
подзапроса:

* перетащите мышкой параметр на поле таблицы или параметр подзапроса с
которым необходимо связать данный параметр, визуально связь будет
представлена линией со стрелкой между полями таблиц/подзапросов;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Для того, чтобы удалить связь, выполните следующие действия:

* выделите связь параметра и поля таблицы или параметра подзапроса;
* нажмите кнопку Delete или используйте комбинацию клавиш Ctrl Delete;
* сохраните элемент приложения нажав кнопку Save All на панели
инструментов Platypus Application Designer или нажав сочетание клавиш
Ctrl Shift S.

Изменения SQL запроса, осуществляемые в визуальном редакторе,
отображаются в тексте на панели SQL Source и наоборот.

Измените SQL-текст в редакторе, например, для того, чтобы добавить
специфические условия, или напишите текст SQL "с нуля". Используйте
инспектор запроса для того, чтобы перетаскивать поля таблиц и параметры
из дерева инспектора непосредственно в текст запроса. Для названий полей
таблиц используйте функцию автозаполнения.

При необходимости для запроса может быть задан специфический текст
SQL-текст диалекта SQL для какой-либо БД. Введите этот текст на вкладке
SQL Dialect Source. При этом необходимо будет ввести текст в поле SQL
Source, который будет использоваться для определения метаданных для
обработки результатов запроса. В случае, если задан специфический текст
SQL, непосредственно при выполнении запроса будет исполняться именно он,
а основной текст SQL будет использован для извлечения метаданных.

__________________________________________________________________________________________________________________________________________________
*Important*

Используйте специфический текст запроса в случае крайней необходимости и
если не нужно обеспечивать переносимость приложения на разные сервера
БД.
__________________________________________________________________________________________________________________________________________________

Поля результатов выполнения запроса определяются автоматически в
результате обработки текста SQL.

_________________________________________________________________________________________
*Important*

Не используйте для псевдонимов полей результатов запроса следующие
имена: `md`, `params`.

Эти имена являются зарезервированными и используются моделью данных в
Platypus.
_________________________________________________________________________________________

Существует возможность изменить тип выходного поля, а также текст его
описания. Для этого выполните следующие действия:

* выберите выходное поле среди узлов выходных полей в инспекторе, и
отредактруйте его свойства в окне редактирования свойств Properties;
* задайте тип выходного поля в свойстве Type, выбрав его из выпадающего
списка;
* введите текст описания выходного поля в свойстве Description.

Для того, чтобы выполнить запрос к базе данных, например, для отладки:

* выберите элемент приложения и выберите пункт Execute контекстного меню
запроса или в контекстном меню редактора SQL-текста SQL Source,
результаты выполнения запроса будут показаны в окне вывода Platypus
Application Designer;
* если у запроса есть параметры, введите их в диалоге выполнения
запроса, при необходимости измените текст запроса в том же диалоге;
* нажмите кнопку OK для выполнения запроса или Cancel для отмены.

Для того, чтобы изменить размер визуального представления запроса:

* нажмите кнопку Zoom In для того, чтобы увеличить, и кнопку Zoom out
для того, чтобы уменьшить диаграмму запроса.

Для того, чтобы воспользоваться поиском по диаграмме запроса:

* нажмите кнопку Find для того, чтобы открыть диалог поиска по диаграмме
запроса;
* введите строку поиска, выберите поля по которым будет осуществляются
поиск: Datasets, Fields, Params, а также установите флажки опций: Whole
words - для поиска целых слов, Match case — для поиска с учетом регистра
символов;
* нажмите кнопки Next и Previous для перехода к следующему результату
поиска;
* нажмите кнопку Close, чтобы закрыть диалог поиска.

[[sql-текст-запроса-к-базе-данных]]
SQL-текст запроса к базе данных
-------------------------------

[[заголовок-запроса]]
Заголовок запроса
~~~~~~~~~~~~~~~~~

Для каждого элемента приложения типа "Запрос" должно быть задано его
имя-идентификатор в рамках приложения в соответствии с общими правилами
формирования имен элементов приложения Platypus. После создания нового
запроса его имя-идентификатор будет задано по имени файла, при этом
пробелы в имени будут заменены символами подчеркивания. После создания
запроса разработчик может изменить его имя.

Для того, чтобы задать имя-идентификатор запроса используйте аннотацию
`@name` в заголовочном блоке запроса:

[source,Sql]
----------------------- 
/**
 * Query header example
 * @name AllDocuments
 **/
SELECT * 
FROM Document
-----------------------

Задание имени-идентификатора запроса является обязательным.

Кроме аннотации `@name` в заголовке запроса допустимы комментарии и
другие аннотации.

[[tекст-запроса]]
Tекст запроса
~~~~~~~~~~~~~

Текст запроса на вкладке SQL Source должен соответствовать стандарту
SQL-92. SQL текст размещается под заголовком и может включать в себя
другие комментарии.

Запрос SQL может содержать выборку всех полей вида `SELECT * FROM table`
или лишь тех полей, которые необходимы, с назначением для них
псевдонимов: `SELECT a, b, c FROM table`. В случае использования запроса
выборки первого типа имена свойств, которые будут доступны в коде
JavaScript определяются базой данных по именам колонкок таблицы и могут
быть приведены верхнему или нижнему регистру. Для создания кода,
совместимого с различными базами данных рекомендуется использовать
второй вариант запроса с явным указанием выходных полей запроса.

Запросы в Platypus могут содержать именованные параметры, которые имеют
следующий вид: `:`.

Пример текста SQL запроса, содержащего именованные параметры:

[source,Sql]
---------------------------------------- 
/**
 * Device log for period of time
 * @name Timelog
 **/
SELECT * 
FROM TR_TRACKINGDEVICE_LOG trackingLog
WHERE trackingLog.DEVICE_ID = :deviceId 
AND trackingLog.TIME >= :timeFrom 
AND trackingLog.TIME <= :timeTo
ORDER BY trackingLog.TIME ASC
----------------------------------------

В Platypus запросы могут быть повторно использованы в других запросах.
Для того, чтобы использовать _Запрос_ в качесве подзапроса, включите в
SQL текст его имя:

[source,Sql]
---------------------------------- 
/**
 * Time log priority filter
 * @name Filter
 **/
SELECT * 
FROM Timelog timeLog
WHERE timeLog.PRIORITY > :priority
----------------------------------

В приведенном выше примере в запросе `Filter` в качестве подзапроса
использован запрос с именем `Timelog`.

_____________________________________________________________________________________________________________
*Note*

Если подзапрос содержит параметры, необходимо связать их с параметрами
того запроса, в который он был вложен.
_____________________________________________________________________________________________________________

.

[[сохранение-изменений-данных]]
Сохранение изменений данных
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Запрос типа `SELECT` в качестве результата возвращает набор сущностей
пригодных для обработки JavaScript-кодом. Данные этих сущностей могут
изменятся в процессе работы приложения. Изменения данных будут
автоматически преобразованы в набор SQL-команд при сохранении в БД. Для
работы этого механизма необходимо, чтобы в возвращаемых запросом данных
содержались первичные ключи соответствующих таблиц. Это позволит
JavaScript ORM-у сориентироваться, какие свойства получающихся сущностей
отвечают за их идентификацию.

Для того, чтобы определить, какие таблицы упомянутые в запросе могут
изменяться при помощи этого механизма используйте аннотации `@writable`
... Для этой аннотации укажите список таблиц, используя в качестве
разделителей пробелы. При отсутствии аннотации `@writable` все таблицы
упомянутые в запросе становятся доступны для записи. Для запрета записи
во все таблицы упомянутые в запросе добавьте в заголовок запроса
аннотацию `@readonly`.

В примере приведенном ниже для записи доступна лишь таблица Document:

[source,Sql]
------------------------------- 
/**
 * @name docsCategories
 * @writable Document
 **/
SELECT * 
FROM Document d
INNER JOIN Category c
ON d.CategoryID = c.CATEGORY_ID
-------------------------------

[[безопасность]]
Безопасность
~~~~~~~~~~~~

Доступ к данным, находящимся в БД, обычно должен быть разграничен для
разных групп пользователей. В Platypus встроен механизм безопасности,
реализующий разграничения доступа к ресурсам на основе ролей текущего
пользователя (пользователя, от имени которого выполняется текущее
действие).

Для того, чтобы ограничить доступ к запросу для определенных ролей,
добавьте в заголовок запроса аннотацию `@rolesAllowed` ... Для
добавленной аннотации укажите список ролей, используя в качестве
разделителей пробелы. Роли, перечисленные в аннотации `@rolesAllowed`
получают права как на чтение, так и на запись данных в БД. В случае,
если необходимо более точное определение политики доступа к данным,
используйте аннотации `@rolesAllowedRead` и `@rolesAllowedWrite`.

Укажите список ролей для которых доступно только чтение данных в
аннотации `@rolesAllowedRead`.

Укажите список ролей для которых доступна только запись данных в
аннотации `@rolesAllowedWrite`.

В случае, если ни одна из аннотаций `@rolesAllowed`, `@rolesAllowedRead`
или `@rolesAllowedWrite` не указана для запроса, данные БД, которыми
манипулирует запрос, доступны как для чтения так и для записи для любого
пользователя.

Пример запроса, для которого права как на чтение, так и на запись
ограничены ролью `admin`:

[source,Sql]
---------------------- 
/**
 * @name AllCategories
 * @rolesAllowed admin
 **/
SELECT * 
FROM Category
----------------------
