[[что-такое-платформа-platypus]]
Что такое Платформа Platypus?
-----------------------------

Platypus Platform - разработанная в компании "Альтернатива-Софт"
инструментальная платформа, предназначенная для построения приложений
любого уровня сложности.

Platypus Platform реализована на базе технологии Java SE, Java EE, GWT и
включает следующие элементы:

* клиентское приложение Platypus Client;
* сервер приложений Platypus Application Server;
* сервлет J2EE сервера со встроенным браузерным клиентом приложений
Platypus Platform;
* дизайнер приложений Platypus Application Designer.

Platypus Application Designer позволяет разрабатывать структуру базы
данных приложения, повторно используемые SQL запросы, клиентскую и
серверную части приложения.

Преимущества инструментальной платформы Platypus:

* Платформа работает на всех операционных системах для которых
реализована виртуальная Java-машина.
* Модули, написанные на внутреннем языке (JavaScript) могут выступать в
качестве внутренних библиотек, модулей форм и отчетов. А также эти
модули возможно разворачивать на сервере приложений в качестве
внутренних серверных задач.
* Многозвенная архитектура с сервером приложений.
* Прозрачная для приложений поддержка разных баз данных.
* Автоматический прозрачный для приложений перенос метаданных из одной
базы данных в другую.
* Web клиент для приложений Platypus.

Поддерживаемые базы данных:

* Oracle;
* Db2;
* MsSql;
* MySql (InnoDb).
* PostgreSql;

Почему выбирают Platypus Platform:

* Инструментальная платформа Platypus Platform подходит для
корпоративной автоматизации.
* Platypus Platform покрывает все задачи обработки и представления
данных в корпоративном информационном пространстве.
* Применённые технические решения ставят платформу на уровень таких
платформ как Sap R/3, Microsoft Dynamics, 1С:Предприятие 8.x.
* Клиент получает более доступное решение по сравнению с западными
аналогами (значительная экономия средств учреждений и предприятий).
* Платформа Platypus Platform отличается максимальной эксплуатационной
простотой, гарантированной скоростью внедрения и надежностью работы.
