[[platforms-installation]]
Platform's installation
-----------------------

If the Platypus Platform runtime is delivered as a ZIP file, unpack its
contents to a location according to your preference on your hard drive.

____________________________________________________________________________________________________________________
*Note*

Instructions for installing the Platypus Application Designer developer
tool are available in the Development Guide.
____________________________________________________________________________________________________________________

[[system-requirements]]
System requirements
-------------------

Below you can see prerequisites for launching the platform components on
your computer:

* 32-bit (x86) or 64-bit (x64) processor running at 1 gigahertz (GHz) or
higher
* 1 gigabyte (GB) (for 32-bit system) or 2 GB (for 64-bit system) RAM
* 5 gigabytes (GB) of free hard disk space
* Windows, Linux, Mac OS X or other operating system like Unix
* Oracle JRE 7 or OpenJDK 7
* Graphical user interface for client operation
* Internet access for downloading updates and working with external
mapping service (In a corporate network, Internet access may be arranged
through a proxy server.)
* Google Chrome 19, Mozilla Firefox 10, Internet Explorer 9 or newer
versions of browsers for Platypus client HTML5 operation

The Platypus Platform supports the following database servers:

* Oracle Database 10g and higher
* IBM DB2 9 and higher
* Microsoft SQL Server 2008 and higher
* MySQL (InnoDB) 5.5 and higher
* PostgreSQL 9 and higher
* H2 Database 1.3 and higher

For information on installing and configuring the database server, refer
to the relevant installation and administration manuals, provided by
database server manufacturers.

The platform runtime is supplied with the H2 database. This database
does not require any additional installation and configuration steps.

For running applicatons on server side in a J2EE servlet container use a
J2EE server or container, for example:

* Apache Tomcat 7
* Glassfish 3.1.2
* JBoss AS7

For information on installing and configuring the servlet container or
J2EE server, refer to the relevant installation and administration
manuals, provided by their manufacturers.

[[installation-guide]]
Installation guide
------------------

To install the platform components, perform the following actions:

1.  Go to the `install` subdirectory of the Platypus distribution kit.
2.  Run `install.bat` files for the Windows OS or perform the
`sh install.sh` command for Linux.
3.  Select the language of the installation program user interface.
4.  Select the installation directory.
5.  Select components to be installed.
* The platform's core components (required)
* Java SE desktop client
* Geospacial and maps components
* Components required for operation of the standalone application server
and in J2EE servlet containers and on the application servers
* Components required for operation with COM/DCOM and OPC servers
6.  Select settings of shortcuts for running the Platypus client in your
system environment.

After installation, the platform's directory will have the following
structure:

* `platypus/`
** `bin/`
** `lib/`
** `etc/`
** `run/`
** `logs/`

[[uninstallation-guide]]
Uninstallation guide
--------------------

To delete the platform components from your computer, perform the
following actions:

* Select the UninstallPlatypus menu item from the installed programs
menu. For Windows, use the conventional mechanism for removing programs.
* Confirm uninstalling of Platypus components. If necessary, enable an
option for removing the working directory.
