[[platforms-installation]]
Platform.js's installation
==========================

If the Platypus.js runtime is delivered as a ZIP file, unpack its
contents to a location according to your preference on your hard drive.

____________________________________________________________________________________________________________________
*Note*

Instructions for installing the Platypus Application Designer developer
tool are available in the Development Guide.
____________________________________________________________________________________________________________________

[[system-requirements]]
System requirements
-------------------

Below you can see prerequisites for launching the platform components on
your computer:

* 32-bit (x86) or 64-bit (x64) processor running at 1 gigahertz (GHz) or
higher
* 1 gigabyte (GB) (for 32-bit system) or 2 GB (for 64-bit system) RAM
* 5 gigabytes (GB) of free hard disk space
* Windows, Linux, Mac OS X or other operating system like Unix
* JDK 8u66+
* Graphical user interface for client operation
* Internet access for downloading updates and working with external
mapping service (In a corporate network, Internet access may be arranged
through a proxy server.)
* Google Chrome 19, Mozilla Firefox 10, Internet Explorer 9 or newer
versions of browsers for Platypus HTML5 client operation

The Platypus.js runtime supports all Jdbc compitible databases.

The Platypus Application database structure designer supports the following database servers:

* Oracle Database 10g and higher
* IBM DB2 9 and higher
* Microsoft SQL Server 2008 and higher
* MySQL (InnoDB) 5.5 and higher
* PostgreSQL 9 and higher
* H2 Database 1.3 and higher

For information on installing and configuring the database server, refer
to the relevant installation and administration manuals, provided by
database server manufacturers.

The platform runtime is supplied with the H2 database. This database
does not require any additional installation and configuration steps.

For running applicatons on server side in a J2EE servlet container use a
J2EE server or container, for example:

* Apache Tomcat 8.0.24 or higher
* WildFly 9.0.0 or higher
* Any J2EE compliant server, probably with some specific settings

For information on installing and configuring the servlet container or
J2EE server, refer to the relevant installation and administration
manuals, provided by their manufacturers.

[[installation-guide]]
Installation guide
------------------

To install the Platform.js runtime, unpack *.zip
file you have downloaded to the desired directory.

After installation, the platform's directory will have the following
structure:

* `platypus/`
** `api/`
** `bin/`
** `etc/`
** `ext/`
** `lib/`
** `updates/`

You might whant to install Platypus.js runtime as part of All-in-one bundle installer.
If so, perform the following actions:

1.  Run downloaded installer file.
2.  Select components (Platypus.js runtime, Platypus Application Designer, Apache Tomcat server) to be installed.
3.  Select the installation directories.

[[uninstallation-guide]]
Uninstallation guide
--------------------
If you have unpacked platypus.js from *.zip file manually, delete platypus directory from your hard disk.
If you have installed platypus.js using All-in-one bundle installer, than perform the
following actions:

* Select the Platypus.js runtime menu item from the installed programs
menu. For Windows, use the conventional mechanism for removing programs.
* Confirm uninstalling of Platypus.js runtime. If necessary, enable an
option for removing the working directory.
