[[application-management]]
Application management
======================
[[security]]
Security
--------

Platypus platform is equipped with security mechanisms and provides
restricted access to system resources based on roles. Roles are
introduced on application level.

As for authentication, Platypus may use various security domains. The
security domain may be internal or external and contain information
about users and their group membership. The following security domain
options are avaliable:

* An database users registry, which is located in two database tables.
This option provides simple tools for storing information about users
and groups.
* External storages of authentication data, for example, a LDAP server
(Active Directory, OpenLDAP, etc.).

The security domain is used to define a set of groups or global roles
for the user, which can be associated with roles at the application
level.

When using database users registry mode, user information is stored in
the `MTD_USERS` table of the application database. Information about the
groups, which the user belongs to, are stored in the `MTD_GROUPS` table.

The `MTD_USERS` table contains the following mandatory fields:

[cols="<,<",options="header",]
|===================================================================
|Field |Description
|`USR_NAME` |Username
|`USR_PASSWD` |Hash sum of the user password using the MD5 algorithm
|===================================================================

In addition, the `MTD_USERS` table can include optional fields
containing additional information about the user.

The `MTD_GROUPS` table contains the following mandatory fields:

[cols="<,<",options="header",]
|========================
|Field |Description
|`USR_NAME` |Username
|`GROUP_NAME` |Group name
|========================

To init the users and user groups tables use the management utility
command line with the the following options:

.Command for creating users and users group table
[cols="<,<",]
|=======================================================================
|Parameter |Description

|`-initusers` |Checks and initializes users database store tables if
they are not initialized
|=======================================================================

After initialization users and groups tables are filled with the default
credentials as follows: `admin` as username and `masterkey` as a
password. The `admin` user is a member of the `admin` group.

_________________________________________________________________________________________
*Important*

Change the default username and password before shipping your
application for production.
_________________________________________________________________________________________
