[[platypus-application-server]]
Platypus Application Server
---------------------------

The main purpose of use of the Platypus Application TSA Server is to provide
support for various binary communication protocols.

[[running-server]]
Running server
--------------

To start the server application, you run the startup shell script for the
server, which contains java command and its command line arguments.

[[command-line-options]]
Command line options
--------------------

The command for running the server is as follows:

------------------------------------------------
java JVM_OPTIONS -cp EXT_CLASSPATH com.eas.server.ServerMain OPTIONS
------------------------------------------------

where JVM_OPTIONS is Java Virtual Machine options, EXT_CLASSPATH are
paths to be added to the Java class loader search path, OPTIONS are
server running parameters.

.Command line options
[cols="<,<",options="header",]
|=======================================================================
|Parameter |Description
|`-iface`ADRESS:PORT,ADRESS:PORT |Network interfaces and listening ports
for the server.

|`-url URL` |URL to the applicaion. Can be one of the follow: `file://`
to specify to a directory or `jndi://` to specify to a datasource.

|`-appelement APP_ELEMENT` |Module or form element's name to run.

|`-protocols` PORT:PROTOCOL,PORT:PROTOCOL |Network protocols for
listening ports.

|`-default-datasource DEFAULT_DS` |Name of the application's default
datasource.

|`-datasource DS` |Datasource name.

|`-dburl DB_URL` |JDBC URL database connection.

|`-dbuser DB_USER` |Username for authorization in the database.

|`-dbpassword DB_PASSWORD` |Password for authorization in the database.

|`-dbschema DB_SCHEMA` |Database scheme (optional).
|=======================================================================

Define zero or more datasources for a single application. A datasource
is represented in a group of the following parameters: `-datasource`,
`-dburl`, `-dbuser,` `-dbpassword` and optional `-dbschema` provided
jointly. One of the datasource can be specified as a default using the
`-default-datasource` parameter.

The example of the application server running command:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp ""C:\Program Files\PlatypusJs\bin\Server.jar;C:\Program Files\PlatypusJs\api;C:\Program Files\PlatypusJs\ext/*;C:\Program Files\PlatypusJs\ext"" com.eas.server.ServerMain -datasource test_db -dburl jdbc:h2:tcp://localhost/~/test_db -dbuser sa -dbpassword sa -dbschema PUBLIC -datasource eas -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser eas -dbpassword eas -dbschema EAS -datasource easHR -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser hr -dbpassword hr -dbschema HR -default-datasource test_db -appelement start.js -url file:/C:/Users/mg/Documents/NetBeansProjects/probah2/ -iface 0.0.0.0:8500 -protocols 8500:platypus
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
